// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guild.sql

package db

import (
	"context"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (name, total_money, daily_limit)
VALUES ($1, $2, $3)
    RETURNING id, name, total_money, reserved_money, daily_limit, daily_spent
`

type CreateGuildParams struct {
	Name       string
	TotalMoney int64
	DailyLimit int64
}

func (q *Queries) CreateGuild(ctx context.Context, arg *CreateGuildParams) (*Guild, error) {
	row := q.db.QueryRow(ctx, createGuild, arg.Name, arg.TotalMoney, arg.DailyLimit)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, total_money, reserved_money, daily_limit, daily_spent FROM guilds WHERE id = $1
`

func (q *Queries) GetGuild(ctx context.Context, id int64) (*Guild, error) {
	row := q.db.QueryRow(ctx, getGuild, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const getGuildForUpdate = `-- name: GetGuildForUpdate :one
SELECT id, name, total_money, reserved_money, daily_limit, daily_spent FROM guilds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetGuildForUpdate(ctx context.Context, id int64) (*Guild, error) {
	row := q.db.QueryRow(ctx, getGuildForUpdate, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const resetDailySpent = `-- name: ResetDailySpent :exec
UPDATE guilds SET daily_spent = 0
`

func (q *Queries) ResetDailySpent(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDailySpent)
	return err
}

const topUpGuildWallet = `-- name: TopUpGuildWallet :one
UPDATE guilds
SET total_money = total_money + $1
WHERE id = $2
    RETURNING id, name, total_money, reserved_money, daily_limit, daily_spent
`

type TopUpGuildWalletParams struct {
	Amount int64
	ID     int64
}

func (q *Queries) TopUpGuildWallet(ctx context.Context, arg *TopUpGuildWalletParams) (*Guild, error) {
	row := q.db.QueryRow(ctx, topUpGuildWallet, arg.Amount, arg.ID)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}

const updateGuildWallet = `-- name: UpdateGuildWallet :one
UPDATE guilds
SET total_money    = $2,
    reserved_money = $3,
    daily_spent    = $4
WHERE id = $1
    RETURNING id, name, total_money, reserved_money, daily_limit, daily_spent
`

type UpdateGuildWalletParams struct {
	ID            int64
	TotalMoney    int64
	ReservedMoney int64
	DailySpent    int64
}

func (q *Queries) UpdateGuildWallet(ctx context.Context, arg *UpdateGuildWalletParams) (*Guild, error) {
	row := q.db.QueryRow(ctx, updateGuildWallet,
		arg.ID,
		arg.TotalMoney,
		arg.ReservedMoney,
		arg.DailySpent,
	)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TotalMoney,
		&i.ReservedMoney,
		&i.DailyLimit,
		&i.DailySpent,
	)
	return &i, err
}
