// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item.sql

package db

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (name, type, status, owner_id)
VALUES ($1, $2, $3, $4)
    RETURNING id, name, type, status, owner_id
`

type CreateItemParams struct {
	Name    string
	Type    ItemType
	Status  ItemStatus
	OwnerID int64
}

func (q *Queries) CreateItem(ctx context.Context, arg *CreateItemParams) (*Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Type,
		arg.Status,
		arg.OwnerID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
	)
	return &i, err
}

const getItem = `-- name: GetItem :one
SELECT id, name, type, status, owner_id FROM items WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (*Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
	)
	return &i, err
}

const getItemForUpdate = `-- name: GetItemForUpdate :one
SELECT id, name, type, status, owner_id FROM items WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetItemForUpdate(ctx context.Context, id int64) (*Item, error) {
	row := q.db.QueryRow(ctx, getItemForUpdate, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
	)
	return &i, err
}

const listItems = `-- name: ListItems :many
SELECT id, name, type, status, owner_id FROM items
`

func (q *Queries) ListItems(ctx context.Context) ([]*Item, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByOwner = `-- name: ListItemsByOwner :many
SELECT id, name, type, status, owner_id FROM items WHERE owner_id = $1
`

func (q *Queries) ListItemsByOwner(ctx context.Context, ownerID int64) ([]*Item, error) {
	rows, err := q.db.Query(ctx, listItemsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemOwner = `-- name: UpdateItemOwner :one
UPDATE items SET owner_id = $2, status = 'available' WHERE id = $1 RETURNING id, name, type, status, owner_id
`

type UpdateItemOwnerParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) UpdateItemOwner(ctx context.Context, arg *UpdateItemOwnerParams) (*Item, error) {
	row := q.db.QueryRow(ctx, updateItemOwner, arg.ID, arg.OwnerID)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
	)
	return &i, err
}

const updateItemStatus = `-- name: UpdateItemStatus :one
UPDATE items SET status = $2 WHERE id = $1 RETURNING id, name, type, status, owner_id
`

type UpdateItemStatusParams struct {
	ID     int64
	Status ItemStatus
}

func (q *Queries) UpdateItemStatus(ctx context.Context, arg *UpdateItemStatusParams) (*Item, error) {
	row := q.db.QueryRow(ctx, updateItemStatus, arg.ID, arg.Status)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.OwnerID,
	)
	return &i, err
}
